# Site settings
baseurl = "https://testing.ullmann.space"
languageCode = "de-de"
title = "Christopher Street Day Wiesbaden"
theme = "syna"
enableGitInfo = true
version = "0.16.1"

[outputs]
  home = ["HTML", "JSON"]

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
     unsafe = true

[params]
  name = "Christopher Street Day Wiesbaden"
  description = "Rahmenprogramm | Demo | Sommerfest | Party"

  [params.style]
    #background = "secondary"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "favicon.ico"
    favicon_ico_sizes = "16x16 32x32"
    favicon_png = "favicon.png"
    favicon_svg = "favicon.svg"

  # Optional, global disable switch for fontawesome related files
  # For custom fontawesome js files use the custom.js method
  [params.fontawesome]
    disabled = false
    pro = false

  [params.colors]
    primary = "#000000"
    secondary = "#000000"
    success = "#008f54"
    info = "#00c9dc"
    warning = "#fdf314"
    danger = "#dc1200"
    light = "#ffffff"
    dark = "#343a40"

# main/prepend/postpend menus are displayed in nav fragment.
# Keep an eye out for updates. These will be moved out to make navbar more
# configurable.
[[menu.main]]
  url = "/kontakt"
  name = "Kontakt"
  weight = 30

[[menu.copyright_footer]]
  url = "/impressum"
  name = "Impressum"
  weight = 10

[[menu.footer_social]]
  weight = 20
  name = "facebook"
  pre = "fab fa-facebook-f"
  url = "https://www.facebook.com/CSDWiesbaden"

[[menu.footer_social]]
  weight = 30
  name = "instagram"
  pre = "fab fa-instagram"
  url = "https://www.instagram.com/csdwiesbaden/"
